# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: shopify_user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      main_id_type: main_id
      edge_sources:
        - inputs/rsIdentifies
        - inputs/rsTracks
        - inputs/rsPages
        - inputs/rsOrderCreated
        - inputs/rsOrderCancelled
        - inputs/rsCartUpdate
        - inputs/rsCartCreate
        - inputs/rsTracksUnionPages
        - inputs/rsCartCreateUnionCartUpdate
        - inputs/rsCART_LINE_ITEMS
        - inputs/rsLAST_CART_STATUS
        - inputs/rsORDER_CREATED_ORDER_CANCELLED
        - inputs/rsITEMS_PURCHASED_EVER

   
# Remove the section below, if you don't want to generate a feature table
  - name: shopify_user_features
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      vars:
        - entityvar:
            name: max_timestamp_tracks
            select: max(timestamp)
            from: inputs/rsTracks

        - entityvar:
            name: max_timestamp_pages
            select: max(timestamp)
            from: inputs/rsPages


        - entityvar:
            name: max_timestamp_bw_tracks_pages
            select: CASE WHEN max_timestamp_tracks>=max_timestamp_pages THEN max_timestamp_tracks ELSE max_timestamp_pages END
        #days since last seen
        - entityvar:
            name: days_since_last_seen
            select: datediff(day, date(max_timestamp_bw_tracks_pages),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))
#       #Churn features
        - entityvar:
            name: is_churned_7_days
            select: case when days_since_last_seen > 7 then 1 else 0 end
        
        #days since last cart add
        - entityvar:
            name: max_timestamp_cart_update
            select: max(timestamp)
            from: inputs/rsCartUpdate
        
        - entityvar:
            name: max_timestamp_cart_create
            select: max(timestamp)
            from: inputs/rsCartCreate

        - entityvar:
            name: max_timestamp_bw_cart_create_update
            select: CASE WHEN max_timestamp_cart_update>=max_timestamp_cart_create THEN max_timestamp_cart_update ELSE max_timestamp_cart_create end
       
        - entityvar:
            name: days_since_last_cart_add
            select: datediff(day, date(max_timestamp_bw_cart_create_update), date('{{timestamp.Format("2006-01-02 15:04:05")}}'))
       
        #total refund
        - entityvar:
            name: total_refund
            select: sum(total_price_usd ::real)
            from: inputs/rsOrderCancelled
            where: financial_status in ('paid','refunded','partially_refunded')

        #refund count
        - entityvar:
            name: refund_count
            select: count(*)
            from: inputs/rsOrderCancelled
            where: financial_status in ('paid','refunded','partially_refunded')

    #days since last purchase
        
        - entityvar:
            name: max_timestamp_order_created
            select: max(timestamp)
            from: inputs/rsOrderCreated
        
        - entityvar:
            name: days_since_last_purchase
            select: datediff(day, date(max_timestamp_order_created), date('{{timestamp.Format("2006-01-02 15:04:05")}}'))
    #days since first purchase

        - entityvar:
            name: min_timestamp_order_created
            select: min(timestamp)
            from: inputs/rsOrderCreated

        - entityvar:
            name: days_since_first_purchase
            select: datediff(day, date(min_timestamp_order_created), date('{{timestamp.Format("2006-01-02 15:04:05")}}'))

    #has credit card
        - entityvar:
            name: has_credit_card
            select: max(case when lower(payment_details_credit_card_company) in ('visa','american express','mastercard') then 1 else 0 end)
            from: inputs/rsOrderCreated

    #avg_units_per_transaction
        - entityvar:
            name: avg_units_per_transaction
            select: avg({{ array_size ( 'products' )}}::real)
            from: inputs/rsOrderCreated

    #avg_transaction_value
        - entityvar:
            name: avg_transaction_value
            select: avg( total_price_usd ::real)
            from: inputs/rsOrderCreated

    #highest_transaction_value
        - entityvar:
            name: highest_transaction_value
            select: max(total_price_usd ::real)
            from: inputs/rsOrderCreated

    #median_transaction_value   
        - entityvar:
            name: median_transaction_value
            select: median( total_price_usd ::real)
            from: inputs/rsOrderCreated

    #total_transactions
        - entityvar:
            name: total_transactions
            select: count(*)
            from: inputs/rsOrderCreated

    #total_refund_in_past_1_days
        - entityvar:
            name: total_refund_in_past_1_days
            select: sum(total_price_usd::real)
            from: inputs/rsOrderCancelled
            where: datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=1 and financial_status in ('paid','refunded','partially_refunded')
    #total_refund_in_past_7_days
        - entityvar:
            name: total_refund_in_past_7_days
            select: sum(total_price_usd::real)
            from: inputs/rsOrderCancelled
            where: datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=7  and financial_status in ('paid','refunded','partially_refunded')
        
       
        
        - entityvar:
            name: days_since_account_creation
            select: datediff(days,date(min(timestamp)),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))

            from: inputs/rsIdentifies

        - entityvar:
            name: has_mobile_app
            select: max(case when lower(context_device_type) in ('android', 'ios') then 1 else 0 end)
            from: inputs/rsIdentifies

        - entityvar:
            name: state
            from: inputs/rsIdentifies
            select: first_value(state)
            window:
              order_by: 
              - timestamp desc
            where: state is not null and state!=''

        - entityvar:
            name: country
            from: inputs/rsIdentifies
            select: first_value(address_country)
            window:
              order_by: 
              - timestamp desc
            where: address_country is not null and address_country!=''


        - entityvar:
            name: first_name
            from: inputs/rsIdentifies
            select: first_value(first_name)
            window:
              order_by: 
              - timestamp desc
            where: first_name is not null and first_name!=''
        - entityvar:
            name: last_name
            from: inputs/rsIdentifies
            select: first_value(last_name)
            window:
              order_by: 
              - timestamp desc
            where: last_name is not null and last_name!=''
        - entityvar:
            name: currency
            from: inputs/rsIdentifies
            select: first_value(currency)
            window:
              order_by: 
              - timestamp desc
            where: currency is not null and currency!=''

        - entityvar:
            name: device_name
            from: inputs/rsIdentifies
            select: first_value(context_device_name)
            window:
              order_by: 
              - timestamp desc
            where: context_device_name is not null and context_device_name!=''
        - entityvar:
            name: device_type
            from: inputs/rsIdentifies
            select: first_value(context_device_type)
            window:
              order_by: 
              - timestamp desc
            where: context_device_type is not null and context_device_type!=''
        
        - entityvar:
            name: campaign_sources
            select: array_agg( context_campaign_source )
            from: inputs/rsIdentifies
       
        - entityvar:
            name: is_active_on_website
            select: max(case when lower(context_device_type) like '%pc' then 1 else 0 end)
            from: inputs/rsIdentifies

        - entityvar:
            name: device_manufacturer
            from: inputs/rsIdentifies
            select: first_value(context_device_manufacturer)
            window:
              order_by: 
              - timestamp desc
            where: context_device_manufacturer is not null and context_device_manufacturer!='' 
        
        - entityvar:
            name: active_days_in_past_7_days
            select: count(distinct date(timestamp))
            from: inputs/rsTracksUnionPages
            where:  datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 7 
        
        - entityvar:
            name: active_days_in_past_365_days
            select: count(distinct date(timestamp))
            from: inputs/rsTracksUnionPages
            where:  datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 365 
        - inputvar:
            name: session_start_time
            from: inputs/rsTracksUnionPages
            select: min(timestamp)
            window:
               partition_by:
                  - context_session_id
                  - main_id
        - inputvar:
            name: session_end_time
            from: inputs/rsTracksUnionPages
            select: max(timestamp)
            window:
               partition_by:
                  - context_session_id
                  - main_id
        - inputvar:
            name: session_row_number
            from: inputs/rsTracksUnionPages
            select: row_number()
            window:
                partition_by: 
                   - context_session_id
                   - main_id
                order_by:
                   - timestamp desc
        - entityvar:
            name: total_sessions_till_date
            from: inputs/rsTracksUnionPages
            select: count(distinct context_session_id)
            where: context_session_id is not null

        - entityvar:
            name: total_sessions_last_week
            from: inputs/rsTracksUnionPages
            select: count(distinct context_session_id)
            where: context_session_id is not null and datediff(day, date(session_start_time), date('{{timestamp.Format("2006-01-02 15:04:05")}}')) between 0 and 7
        - entityvar:
            name: total_sessions_90_days
            from: inputs/rsTracksUnionPages
            select: count(distinct context_session_id)
            where: context_session_id is not null and datediff(day, date(session_start_time), date('{{timestamp.Format("2006-01-02 15:04:05")}}')) between 0 and 90
        - entityvar:
            name: total_sessions_365_days
            from: inputs/rsTracksUnionPages
            select: count(distinct context_session_id)
            where: context_session_id is not null and datediff(day, date(session_start_time), date('{{timestamp.Format("2006-01-02 15:04:05")}}')) between 0 and 365

        - entityvar:
            name: avg_session_length_in_sec_overall
            from: inputs/rsTracksUnionPages
            select: avg(datediff(second, session_start_time, session_end_time))
            where: session_row_number = 1 and context_session_id is not null


        - entityvar:
            name: avg_session_length_in_sec_last_week
            from: inputs/rsTracksUnionPages
            select: avg(datediff(second, session_start_time, session_end_time))
            where: context_session_id is not null and session_row_number = 1 and datediff(day, date(session_start_time), date('{{timestamp.Format("2006-01-02 15:04:05")}}')) between 0 and 7
        - entityvar:
            name: avg_session_length_in_sec_365_days
            from: inputs/rsTracksUnionPages
            select: avg(datediff(second, session_start_time, session_end_time))
            where: context_session_id is not null and session_row_number = 1 and datediff(day, date(session_start_time), date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=365

        - entityvar:
            name: first_seen_date
            from: inputs/rsTracksUnionPages
            select: min(date(session_start_time))
        - entityvar:
            name: last_seen_date
            from: inputs/rsTracksUnionPages
            select: max(date(session_end_time))
        - entityvar:
            name: carts_in_past_1_days
            select: count(distinct token)
            from: inputs/rsCartCreateUnionCartUpdate
            where:  datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 1 
        - entityvar:
            name: carts_in_past_7_days
            select: count(distinct token)
            from: inputs/rsCartCreateUnionCartUpdate
            where:  datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 7 
        - entityvar:
            name: carts_in_past_365_days
            select: count(distinct token)
            from: inputs/rsCartCreateUnionCartUpdate
            where:  datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 365 
        - entityvar:
            name: total_carts
            select: count(distinct token)
            from: inputs/rsCartCreateUnionCartUpdate

        
        - entityvar:
            name: last_transaction_value
            from: inputs/rsOrderCreated
            select: first_value(total_price_usd)
            window:
              order_by: 
              - case when TOTAL_PRICE_USD is not null then 2 else 1 end desc
              - timestamp desc

        
        - entityvar:
            name: total_products_added
            select: array_agg(distinct product_id)
            from: inputs/rsCART_LINE_ITEMS

        - entityvar:
            name: products_added_in_past_1_days
            select: array_agg(distinct product_id)
            from: inputs/rsCART_LINE_ITEMS
            where: datediff(day, date(timestamp), date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 1
        - entityvar:
            name: products_added_in_past_7_days
            select: array_agg(distinct product_id)
            from: inputs/rsCART_LINE_ITEMS
            where: datediff(day, date(timestamp), date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 7
        - entityvar:
            name: products_added_in_past_365_days
            select: array_agg(distinct product_id)
            from: inputs/rsCART_LINE_ITEMS
            where: datediff(day, date(timestamp), date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 365
        

        - entityvar:
            name: last_cart_value_in_dollars
            select: sum(line_price)
            from: inputs/rsCART_LINE_ITEMS
        - entityvar:
            name: last_cart_status
            select: min(coalesce(fulfillment_status, financial_status, 'abandoned'))
            from: inputs/rsORDER_CREATED_ORDER_CANCELLED
        - entityvar:
            name: transactions_in_past_1_days
            select: count(*)::real
            from: inputs/rsORDER_CREATED_ORDER_CANCELLED
            where: datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=1

        - entityvar:
            name: transactions_in_past_90_days
            select: count(*)::real
            from: inputs/rsORDER_CREATED_ORDER_CANCELLED
            where: datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=90

        - entityvar:
            name: transactions_in_past_365_days
            select: count(*)::real
            from: inputs/rsORDER_CREATED_ORDER_CANCELLED
            where: datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=365
        - entityvar:
            name: net_amt_spent_in_past_90_days
            select: sum(total_price_usd::real) - coalesce(sum(total_price_usd_order_cancelled::real), 0)
            from: inputs/rsORDER_CREATED_ORDER_CANCELLED
            where: datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=90

        - entityvar:
            name: net_amt_spent_in_past_365_days
            select: sum(total_price_usd::real) - coalesce(sum(total_price_usd_order_cancelled::real), 0)
            from: inputs/rsORDER_CREATED_ORDER_CANCELLED
            where: datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=365

        - entityvar:
            name: net_amt_spent_in_past_1_days
            select: sum(total_price_usd::real) - coalesce(sum(total_price_usd_order_cancelled::real), 0)
            from: inputs/rsORDER_CREATED_ORDER_CANCELLED
            where: datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=1
        - entityvar:
            name: net_amt_spent_in_past
            select: sum(total_price_usd::real) - coalesce(sum(total_price_usd_order_cancelled::real), 0)
            from: inputs/rsORDER_CREATED_ORDER_CANCELLED
        - entityvar:
            name: gross_amt_spent_in_past
            select: sum(total_price_usd::real)
            from: inputs/rsORDER_CREATED_ORDER_CANCELLED
        - entityvar:
            name: items_purchased_ever
            select: array_agg(sku)
            from: inputs/rsITEMS_PURCHASED_EVER
    




      features:
        - days_since_last_seen
        - is_churned_7_days
        - days_since_last_cart_add
        - total_refund
        - refund_count
        - days_since_last_purchase
        - days_since_first_purchase
        - has_credit_card
        - avg_units_per_transaction
        - avg_transaction_value
        - highest_transaction_value
        - median_transaction_value
        - total_transactions
        - total_refund_in_past_1_days
        - total_refund_in_past_7_days
        - days_since_account_creation
        - has_mobile_app
        - state
        - country
        - first_name
        - last_name
        - currency
        - device_type
        - device_name
        - campaign_sources
        - is_active_on_website
        - device_manufacturer
        - active_days_in_past_7_days
        - active_days_in_past_365_days
        - total_sessions_till_date
        - total_sessions_last_week
        - avg_session_length_in_sec_overall
        - avg_session_length_in_sec_last_week
        - avg_session_length_in_sec_365_days
        - first_seen_date
        - last_seen_date
        - carts_in_past_1_days
        - carts_in_past_7_days
        - carts_in_past_365_days
        - total_carts
        - last_transaction_value
        - total_products_added
        - products_added_in_past_1_days
        - products_added_in_past_7_days
        - products_added_in_past_365_days
        - total_sessions_90_days
        - total_sessions_365_days
        - last_cart_status
        - last_cart_value_in_dollars
        - transactions_in_past_1_days
        - transactions_in_past_90_days
        - transactions_in_past_365_days
        - net_amt_spent_in_past_1_days
        - net_amt_spent_in_past_90_days
        - net_amt_spent_in_past_365_days
        - net_amt_spent_in_past
        - gross_amt_spent_in_past
        - items_purchased_ever

