models:
  - name: rudder_user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
          # Remove the section below, if you don't want to generate a feature table
  - name: pages_orderby_table
    model_type: sql_template
    model_spec:
      validity_time: 24h # 1 day
      materialization:
        output_type: ephemeral
        run_type: discrete
      single_sql: |
        {% with Pages = this.DeRef("inputs/rsPages") %}
            select * from {{Pages}} order by timestamp asc
        {% endwith %}
      ids:
        - select: "user_id"
          type: user_id
          entity: user
          to_default_stitcher: true
        - select: "anonymous_id"
          type: anonymous_id
          entity: user
          to_default_stitcher: true
      contract:
        is_optional: false
        is_event_stream: false
        with_entity_ids:
          - user
        with_columns:
          - name: input_row_id
          - name: user_id
          - name: anonymous_id
          - name: context_session_id
          - name: context_campaign_name
          - name: context_campaign_source
          - name: context_campaign_medium
          - name: timestamp
          - name: user_main_id 
  - name: rudder_user_base_features
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      vars:
        - entity_var:
            name: max_timestamp_bw_tracks_pages
            select:  max({{rsTracksUnionPages.Var("timestamp")}})
            from: models/rsTracksUnionPages
        #days since last seen
        - entity_var:
            name: days_since_last_seen
            select: "{{macro_datediff('{{user.Var(\"max_timestamp_bw_tracks_pages\")}}')}}"
        #Churn features
        - entity_var:
            name: is_churned_7_days
            select: case when {{user.Var("days_since_last_seen")}} > 7 then 1 else 0 end
            description: Depending on the n value, it specifies if there is any activity observed in the last 7 days.
            dependencies:
              - session_end_time
        - entity_var:
            name: days_since_account_creation
            select: "{{macro_datediff('min({{rsIdentifies.Var(\"timestamp\")}})')}}"
            from: inputs/rsIdentifies
        - entity_var:
            name: state
            from: inputs/rsIdentifies
            select: first_value({{rsIdentifies.Var("state")}})
            window:
              order_by:
                - "{{rsIdentifies.Var('timestamp')}} desc"
            where: "{{rsIdentifies.Var('state')}} is not null and {{rsIdentifies.Var('state')}}!=''"
        - entity_var:
            name: country
            from: inputs/rsIdentifies
            select: first_value({{rsIdentifies.Var('address_country')}})
            window:
              order_by:
                - "{{rsIdentifies.Var('timestamp')}} desc"
            where: "{{rsIdentifies.Var('address_country')}} is not null and {{rsIdentifies.Var('address_country')}}!=''"
        - entity_var:
            name: first_name
            from: inputs/rsIdentifies
            select: first_value({{rsIdentifies.Var('first_name')}})
            window:
              order_by:
                - "{{rsIdentifies.Var('timestamp')}} desc"
            where: "{{rsIdentifies.Var('first_name')}} is not null and {{rsIdentifies.Var('first_name')}}!=''"
        - entity_var:
            name: last_name
            from: inputs/rsIdentifies
            select: first_value({{rsIdentifies.Var('last_name')}})
            window:
              order_by:
                - "{{rsIdentifies.Var('timestamp')}} desc"
            where: "{{rsIdentifies.Var('last_name')}} is not null and {{rsIdentifies.Var('last_name')}}!=''"
        - entity_var:
            name: currency
            from: inputs/rsIdentifies
            select: first_value({{rsIdentifies.Var('currency')}})
            window:
              order_by:
                - "{{rsIdentifies.Var('timestamp')}} desc"
            where: "{{rsIdentifies.Var('currency')}} is not null and {{rsIdentifies.Var('currency')}}!=''"
            dependencies:
              - session_start_time
        - entity_var:
            name: campaign_sources
            select: array_agg({{rsIdentifies.Var('context_campaign_source')}})
            from: inputs/rsIdentifies
        - entity_var:
            name: active_days_in_past_7_days
            select: count(distinct date({{rsTracksUnionPages.Var("timestamp")}}))
            from: models/rsTracksUnionPages
            where: "{{macro_datediff_n('{{rsTracksUnionPages.Var(\"timestamp\")}}','7')}}"
            description: Out of 7 days, how many days have recorded an event till date including today
            dependencies:
              - session_start_time
        - entity_var:
            name: active_days_in_past_365_days
            select: count(distinct date({{rsTracksUnionPages.Var('timestamp')}}))
            from: models/rsTracksUnionPages
            where: "{{macro_datediff_n('{{rsTracksUnionPages.Var(\"timestamp\")}}','365')}}"
            description: Out of 365 days, how many days have recorded an event till date including today
        - input_var:
            name: session_start_time
            from: models/rsTracksUnionPages
            select: min({{rsTracksUnionPages.Var('timestamp')}})
            window:
              partition_by:
                - "{{rsTracksUnionPages.Var('context_session_id')}}"
                - "{{rsTracksUnionPages.Var('rudder_id')}}"
            description: Describes the start time of session of a specific context_id
        - input_var:
            name: session_end_time
            from: models/rsTracksUnionPages
            select: max({{rsTracksUnionPages.Var('timestamp')}})
            window:
              partition_by:
                - "{{rsTracksUnionPages.Var('context_session_id')}}"
                - "{{rsTracksUnionPages.Var('rudder_id')}}"
            description: Describes the end time of session of a specific context_id
        - input_var:
            name: session_row_number
            from: models/rsTracksUnionPages
            select: row_number()
            window:
              partition_by:
                - "{{rsTracksUnionPages.Var('context_session_id')}}"
                - "{{rsTracksUnionPages.Var('rudder_id')}}"
              order_by:
                - "{{rsTracksUnionPages.Var('timestamp')}} desc"
            description: A row number for all the events within a single session. This is used to compute some of the session based features/
        - entity_var:
            name: total_sessions_till_date
            from: models/rsTracksUnionPages
            select: count(distinct {{rsTracksUnionPages.Var('context_session_id')}})
            where: "{{rsTracksUnionPages.Var('context_session_id')}} is not null"
            description: Total individual sessions created till date.
        - entity_var:
            name: total_sessions_last_week
            from: models/rsTracksUnionPages
            select: count(distinct {{rsTracksUnionPages.Var('context_session_id')}})
            where: " {{rsTracksUnionPages.Var('context_session_id')}} is not null and {{macro_datediff('{{rsTracksUnionPages.Var(\"session_start_time\")}}')}} between 0 and 7"
            description: total number of sessions over last 7 days.
            dependencies:
              - session_row_number
        - entity_var:
            name: total_sessions_90_days
            from: models/rsTracksUnionPages
            select: count(distinct {{rsTracksUnionPages.Var('context_session_id')}})
            where: " {{rsTracksUnionPages.Var('context_session_id')}} is not null and {{macro_datediff('{{rsTracksUnionPages.Var(\"session_start_time\")}}')}} between 0 and 90"
            description: total number of sessions over last 90 days.
        - entity_var:
            name: total_sessions_365_days
            from: models/rsTracksUnionPages
            select: count(distinct {{rsTracksUnionPages.Var('context_session_id')}})
            where: " {{rsTracksUnionPages.Var('context_session_id')}} is not null and {{macro_datediff('{{rsTracksUnionPages.Var(\"session_start_time\")}}')}} between 0 and 365 "
            description: total number of sessions over last 356 days.
            dependencies:
              - session_start_time
        - entity_var:
            name: avg_session_length_in_sec_overall
            from: models/rsTracksUnionPages
            select: avg(datediff(second, {{rsTracksUnionPages.Var('session_start_time')}}, {{rsTracksUnionPages.Var('session_end_time')}}))
            where: "{{user.Var('session_row_number')}} = 1 and {{rsTracksUnionPages.Var('context_session_id')}} is not null"
            description: Average session length (in seconds) of all the user sessions till date.
            dependencies:
              - session_row_number
              - session_start_time
              - session_end_time
        - entity_var:
            name: avg_session_length_in_sec_last_week
            from: models/rsTracksUnionPages
            select: avg(datediff(second, {{rsTracksUnionPages.Var('session_start_time')}}, {{rsTracksUnionPages.Var('session_end_time')}}))
            where: "{{rsTracksUnionPages.Var('context_session_id')}} is not null and {{user.Var('session_row_number')}} = 1 and {{macro_datediff(\"{{rsTracksUnionPages.Var('session_start_time')}}\")}}  between 0 and 7"
            description: Average session length (in seconds) of all the user sessions that started in last 7 days
            dependencies:
              - session_start_time
              - session_end_time
              - session_row_number
        - entity_var:
            name: avg_session_length_in_sec_365_days
            from: models/rsTracksUnionPages
            select: avg(datediff(second, {{rsTracksUnionPages.Var('session_start_time')}}, {{rsTracksUnionPages.Var('session_end_time')}}))
            where: "{{rsTracksUnionPages.Var('context_session_id')}} is not null and {{user.Var('session_row_number')}} = 1 and {{macro_datediff_n(\"{{rsTracksUnionPages.Var('session_start_time')}}\",'365')}}"
            description: Average session length (in seconds) of all the user sessions that started in last 365 days
            dependencies:
              - session_row_number
              - session_start_time
              - session_end_time
        - entity_var:
            name: first_seen_date
            from: models/rsTracksUnionPages
            select: min(date( {{rsTracksUnionPages.Var('session_start_time')}}))
            description: The first date on which an event has been recorded by the user
            dependencies:
              - session_start_time
        - entity_var:
            name: last_seen_date
            from: models/rsTracksUnionPages
            select: max(date( {{rsTracksUnionPages.Var('session_end_time')}}))
            description: The latest date on which an event has been recorded by the user
            dependencies:
              - session_end_time
        - entity_var:
            name: first_campaign_name
            from: inputs/rsPages
            select: first_value({{rsPages.Var('context_campaign_name')}})
            window:
              order_by:
                - "{{rsPages.Var('timestamp')}} asc"
            where: "{{rsPages.Var('context_campaign_name')}} is not null and {{rsPages.Var('context_campaign_name')}}!=''"
            description: First campaign from which a user has visited the app
        - entity_var:
            name: last_campaign_name
            from: inputs/rsPages
            select: last_value({{rsPages.Var('context_campaign_name')}})
            window:
              order_by:
                - "{{rsPages.Var('timestamp')}} asc"
            where: "{{rsPages.Var('context_campaign_name')}} is not null and {{rsPages.Var('context_campaign_name')}}!=''"
            description: Latest campaign from which a user has visited the app
        - entity_var:
            name: first_source_name
            from: inputs/rsPages
            select: first_value({{rsPages.Var('context_campaign_source')}})
            window:
              order_by:
                - "{{rsPages.Var('timestamp')}} asc"
            where: "{{rsPages.Var('context_campaign_source')}} is not null and {{rsPages.Var('context_campaign_source')}}!=''"
            description: First source from which a user has visited the app
        - entity_var:
            name: last_source_name
            from: inputs/rsPages
            select: last_value({{rsPages.Var('context_campaign_source')}})
            window:
              order_by:
                - "{{rsPages.Var('timestamp')}} asc"
            where: "{{rsPages.Var('context_campaign_source')}} is not null and {{rsPages.Var('context_campaign_source')}}!=''"
            description: Last source from which a user has visited the app
        - entity_var:
            name: campaigns_list
            from: models/pages_orderby_table
            select: array_agg( {{pages_orderby_table.Var('context_campaign_name')}})
            description: list of all campaigns from which a user has visited the app, sorted in chronological order, from oldest to newest
        - entity_var:
            name: mediums_list
            from: models/pages_orderby_table
            select: array_agg( {{pages_orderby_table.Var('context_campaign_medium')}})
            description: list of all mediums from which a user has visited the app, sorted in chronological order, from oldest to newest
        - entity_var:
            name: sources_list
            from: models/pages_orderby_table
            select: array_agg( {{pages_orderby_table.Var('context_campaign_source')}})
            description: list of all sources from which a user has visited the app, sorted in chronological order, from oldest to newest
            dependencies:
              - session_start_time
      features:
        - days_since_last_seen
        - days_since_account_creation
        - state
        - country
        - first_name
        - last_name
        - currency
        - campaign_sources
        - active_days_in_past_7_days
        - active_days_in_past_365_days
        - total_sessions_till_date
        - total_sessions_last_week
        - total_sessions_90_days
        - total_sessions_365_days
        - avg_session_length_in_sec_overall
        - avg_session_length_in_sec_last_week
        - avg_session_length_in_sec_365_days
        - first_seen_date
        - last_seen_date
        - is_churned_7_days
        - first_campaign_name
        - last_campaign_name
        - first_source_name
        - last_source_name
        - campaigns_list
        - mediums_list
        - sources_list