models:
  - name: rudder_user_id_stitcher
    model_type: id_stitcher
    model_spec:
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
          # Remove the section below, if you don't want to generate a feature table
  - name: pages_orderby_table
    model_type: sql_template
    model_spec:
      materialization:
        output_type: ephemeral
        run_type: discrete
      single_sql: |
        {% with Pages = this.DeRef("inputs/rsPages") %}
            select * from {{Pages}} order by timestamp asc
        {% endwith %}
      ids:
        - select: "user_id"
          type: user_id
          entity: user
        - select: "anonymous_id"
          type: anonymous_id
          entity: user
      contract:
        is_optional: false
        is_event_stream: false
        with_entity_ids:
          - user
        with_columns:
          - name: input_row_id
          - name: user_id
          - name: anonymous_id
          - name: context_session_id
          - name: context_campaign_name
          - name: context_campaign_source
          - name: context_campaign_medium
          - name: timestamp
          - name: user_main_id
  - name: rudder_user_base_features
    model_type: feature_table_model
    model_spec:
      entity_key: user
