models:
  - name: rudder_user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
        - from: inputs/rsOrderCompleted
          # Remove the section below, if you don't want to generate a feature table
  - name: pages_orderby_table
    model_type: sql_template
    model_spec:
      validity_time: 24h # 1 day
      materialization:
        output_type: ephemeral
        run_type: discrete
      single_sql: |
        {% with Pages = this.DeRef("inputs/rsPages") %}
            select * from {{Pages}} order by timestamp asc
        {% endwith %}
      ids:
        - select: "user_id"
          type: user_id
          entity: user
          to_default_stitcher: true
        - select: "anonymous_id"
          type: anonymous_id
          entity: user
          to_default_stitcher: true
      contract:
        is_optional: false
        is_event_stream: false
        with_entity_ids:
          - user
        with_columns:
          - name: input_row_id
          - name: user_id
          - name: anonymous_id
          - name: context_session_id
          - name: context_campaign_name
          - name: context_campaign_source
          - name: context_campaign_medium
          - name: timestamp
          - name: user_main_id
  - name: attribution_input_model
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      vars:
        - entity_var:
            name: first_seen_date
            select: min(timestamp)
            from: inputs/rsIdentifies
        - entity_var:
            name: days_since_first_seen
            select: "{{macro_datediff('{{user.Var(\"first_seen_date\")}}')}}"
            dependencies:
              - first_seen_date
        - entity_var:
            name: gross_amt_spent_overall
            default: 0
            select: sum(REVENUE::real)
            from: inputs/rsOrderCompleted
            description: Total amount spent till date.
        - entity_var:
            name: is_payer
            default: 0
            select: case when sum(REVENUE::real) > 0 then 1 else 0 end
            from: inputs/rsOrderCompleted
            description: Whether a customer has ever made a payment
        - entity_var:
            name: campaign_sources
            select: array_agg( context_campaign_source )
            from: inputs/rsIdentifies
        - entity_var:
            name: campaigns_list
            from: models/pages_orderby_table
            select: array_agg( context_campaign_name)
            description: list of all campaigns from which a user has visited the app, sorted in chronological order, from oldest to newest
        - entity_var:
            name: mediums_list
            from: models/pages_orderby_table
            select: array_agg( context_campaign_medium)
            description: list of all mediums from which a user has visited the app, sorted in chronological order, from oldest to newest
        - entity_var:
            name: sources_list
            from: models/pages_orderby_table
            select: array_agg( context_campaign_source)
            description: list of all sources from which a user has visited the app, sorted in chronological order, from oldest to newest
            dependencies:
              - session_start_time
      features:
        - days_since_first_seen
        - gross_amt_spent_overall
        - is_payer
        - campaign_sources
        - campaigns_list
        - mediums_list
        - sources_list
  - name: attribution_scores_boolean
    model_type: campaign_attribution_scores
    model_spec:
      touchpoint_var: campaigns_list
      days_since_first_seen_var: days_since_first_seen
      first_seen_since: 90
      conversion_entity_var: is_payer
      entity: user

  - name: attribution_scores_revenue
    model_type: campaign_attribution_scores
    model_spec:
      touchpoint_var: campaigns_list
      days_since_first_seen_var: days_since_first_seen
      first_seen_since: 90
      conversion_entity_var: gross_amt_spent_overall
      entity: user      