models:
  - name: rsIdentifies
    model_type: common_column_union
    model_spec:
      inputs:
        - inputs/rsIdentifies_1
        - inputs/rsIdentifies_2
        - inputs/rsIdentifies_3
  - name: rsTracks
    model_type: common_column_union
    model_spec:
      inputs:
        - inputs/rsTracks_1
        - inputs/rsTracks_2
        - inputs/rsTracks_3
  - name: rsPages
    model_type: common_column_union
    model_spec:
      inputs:
        - inputs/rsPages_1
        - inputs/rsPages_2
        - inputs/rsPages_3
  - name: pages_orderby_table
    model_type: sql_template
    model_spec:
      validity_time: 24h # 1 day
      materialization:
        output_type: ephemeral
        run_type: discrete
      single_sql: |
        {% with Pages = this.DeRef("models/rsPages") %}
            select * from {{Pages}} order by timestamp asc
        {% endwith %}
      ids:
        - select: "user_id"
          type: user_id
          entity: user
        - select: "anonymous_id"
          type: anonymous_id
          entity: user
      contract:
        is_optional: false
        is_event_stream: false
        with_entity_ids:
          - user
        with_columns:
          - name: input_row_id
          - name: user_id
          - name: anonymous_id
          - name: context_session_id
          - name: context_campaign_name
          - name: context_campaign_source
          - name: context_campaign_medium
          - name: timestamp
